<?php $helper = Mage::helper("multidealpro") ?>
<meta name="format-detection" content="telephone=no"/>
<script type="text/javascript">
//<![CDATA[
	var em_deal_baseurl 	= '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>';
	var em_now 				= <?php echo $helper->dealtime(); ?>;

	var em_deal_date = {
		day : "<?php echo $helper->__("dia") ?>",
		days : "<?php echo $helper->__("dias") ?>",
		hour : "<?php echo $helper->__("hora") ?>",
		hours : "<?php echo $helper->__("horas") ?>",
		minute : "<?php echo $helper->__("minuto") ?>",
		minutes : "<?php echo $helper->__("minutos") ?>",
		second : "<?php echo $helper->__("segundo") ?>",
		seconds : "<?php echo $helper->__("segundos") ?>"
	};
//]]>
</script>